version: "1"
rules:
    - base: master
      upstream: ODPReactor:master
      autoMerge: true
      autoMergeHardReset: false
    - base: develop
      upstream: ODPReactor:develop
      autoMerge: true
      autoMergeHardReset: false
